# Mayastor DiskPool 示例
# 每个运行 io-engine 的节点都需要一个 DiskPool
# 请确保 disks 列表中的磁盘是未分区、未挂载的裸盘！

---
apiVersion: io.openebs.storage/v1beta2
kind: DiskPool
metadata:
  name: pool-master
  namespace: openebs
spec:
  node: k8s-master-01
  disks:
    - /dev/nvme0n1

---
apiVersion: io.openebs.storage/v1beta2
kind: DiskPool
metadata:
  name: pool-worker-01
  namespace: openebs
spec:
  node: k8s-worker-01
  disks:
    - /dev/nvme0n1

---
apiVersion: io.openebs.storage/v1beta2
kind: DiskPool
metadata:
  name: pool-worker-02
  namespace: openebs
spec:
  node: k8s-worker-02
  disks:
    - /dev/nvme0n1
