# Mayastor 测试 Pod

apiVersion: v1
kind: Pod
metadata:
  name: mayastor-test-pod
  namespace: default
spec:
  containers:
    - name: test
      image: 172.25.128.67:9003/library/busybox:latest
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mayastor-test-pvc
